HOST: http://www.google.ca/

--- Refactor of MyAnimeList Unofficial API Documentation ---
---
This is a refactor of the Unofficial MyAnimeList API. I am attempting to restructure the
application using a different framework (Padrino), modularize each piece of the api, and
have a well defined test suite.
---

-- Anime --

Fetch an anime
GET /anime/:id
< 200

Search for anime
GET /anime/search/:query
< 200

Fetch the upcoming anime
GET /anime/upcoming
< 200

Fetch the just added anime
GET /anime/just_added
< 200

Fetch the top anime
GET /anime/top
< 200

Fetch the most popular anime
GET /anime/popular
< 200

-- Manga --

Fetch a manga
GET /manga/:id
< 200

GET /manga/search/:query
< 200

-- User --

Fetch a users MyAnimeList profile.
GET /user/:username
< 200

Fetch a users anime list.
GET /user/:username/animelist
< 200

Fetch a users manga list.
GET /user/:username/mangalist
< 200

Fetch a users anime and manga history.
GET /user/:username/history
< 200